### PR TITLE
Update fedora offering

### PR DESCRIPTION
**Pull request by ganeshmaharaj**

### CODE REVIEW

**Comment by markdryan** [comment]
@ganeshmaharaj Why not just create new workloads and leave the existing ones intact?  Are the cloud images for fedora29 no longer available?  Sometimes I do find myself needing to create VMs based on old distros.

**Comment by markdryan** [comment]
You've reminded me though.  I have some new ubuntu workloads locally that need pushing.

**Comment by ganeshmaharaj** [comment]
Fedora 27-29 are EOL and no longer officially supported. That's why I removed them. The cloud images are still available. I can leave the files there.

**Comment by markdryan** [comment]
Yeah, let's leave them there.

**Review by markdryan — APPROVED** [review]

**Pull request merged**
